# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mytlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 9, 8, 1, 6017, tzinfo=utc), verbose_name='create date'),
        ),
    ]
